name: Dump Entities from Baserow

on:
  schedule:
  - cron: "33 */12 * * *"
  workflow_dispatch:

jobs:
  download:
    name: dump baserow
    runs-on: ubuntu-latest
    env:
      BASEROW_TOKEN: ${{secrets.BASEROW_TOKEN}}
      BASEROW_USER: ${{secrets.BASEROW_USER}}
      BASEROW_PW: ${{secrets.BASEROW_PW}}
    steps:
      - name: Perfom Checkout
        uses: actions/checkout@v3
      - name: Install Python Packages
        run: |
          pip install -r requirements.txt
      - name: dump the data
        run: |
          python dump_data.py
      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Data update from Baserow